Issue 1 user can look up monsters
jnsangalang/monsters-and-spells-oh-my pull request #6
Opened 2024-05-02 19:49 UTC by jnsangalang

![issue 1 front end project](https://github.com/jnsangalang/front-end-project/assets/157412933/5c4138d6-e7a2-4f62-8c57-dcf597d7bafe)

2024-05-02 23:45 UTC, jnsangalang commented
![issue 1 front end project](https://github.com/jnsangalang/front-end-project/assets/157412933/791d8a74-74d7-4ca1-a11d-405963e398cb)

2024-05-02 23:52 UTC, shawnkost requested changes
Looking great so far Johan! Just a few comments here

2024-05-02 23:52 UTC, shawnkost commented on index.html
> +    <header></header>
Does anything ever get added to this? If no, then go ahead and delete this

2024-05-02 23:52 UTC, shawnkost commented on ts/data.ts
> +// };
Remove all commented out code

2024-05-02 23:52 UTC, shawnkost commented on ts/main.ts
> +// }
Remove all commented out code

2024-05-02 23:52 UTC, shawnkost commented on ts/main.ts
> +  const monstersInfo = responseMonsters.results;
This should be inside your `try` statement

2024-05-02 23:52 UTC, shawnkost commented on ts/main.ts
> +    }
This should be in your `try` statement. Whenever you `throw` an error in your `try`, it will then automatically jump to your `catch` and then pass in the error to the `error` argument. So the `if` statement should go inside the `try` block, along with the `throw new Error`, but you should update the `textContent` inside the `catch`

2024-05-02 23:52 UTC, shawnkost commented on ts/main.ts
> +// }
Remove all commented out code. If this is for a future issue, save it in your notes or something, then add this is when you get there

2024-05-03 15:56 UTC, shawnkost approved these changes
👍🏻

2024-05-03 15:59 UTC, merged